import Painting from '@/components/paintings/painting';
import classes from './index.module.css'

const PAINTINGS = [
    {
      key: "1",
      height: 20,
      width: 16,
      dimensions: "20 на 16",
      enDimensions: "20 to 16",
      name: "CV снимка",
      enName: "CV Photo",
      technique: "акрил, смесена техника",
      enTechnique: "acrylic, mixed media",
      продадена: false,
      sold: false,
    },
    {
      key: "2",
      height: 20,
      width: 16,
      dimensions: "20 на 16",
      enDimensions: "20 to 16",
      name: "Мишел",
      enName: "Mishel",
      technique: "акрил, смесена техника",
      enTechnique: "acrylic, mixed media",
      продадена: false,
      sold: false,
    },
    {
      key: "3",
      height: 20,
      width: 16,
      dimensions: "20 на 16",
      enDimensions: "20 to 16",
      name: "Невинно синьо пиле",
      enName: "Innocent Blue Bird",
      technique: "акрил, смесена техника",
      enTechnique: "acrylic, mixed media",
      продадена: false,
      sold: false,
    },
    {
      key: "4",
      height: 20,
      width: 16,
      dimensions: "20 на 16",
      enDimensions: "20 to 16",
      name: "Сънотворна река",
      enName: "Dream River",
      technique: "акрил, смесена техника",
      enTechnique: "acrylic, mixed media",
      продадена: false,
      sold: false,
    }, 
    {
      key: "5",
      height: 30,
      width: 25,
      dimensions: "30 на 25",
      enDimensions: "30 to 25",
      name: "Изгубената маска",
      enName: "The Lost Mask",
      technique: "акрил, смесена техника",
      enTechnique: "acrylic, mixed media",
      продадена: false,
      sold: false,
    }, 
    {
      key: "6",
      height: 30,
      width: 25,
      dimensions: "30 на 25",
      enDimensions: "30 to 25",
      name: "Панеленият град",
      enName: "Panelcity",
      technique: "акрил, смесена техника",
      enTechnique: "acrylic, mixed media",
      продадена: false,
      sold: false,
    },  
    {
      key: "7",
      height: 29,
      width: 20,
      dimensions: "29 на 20",
      enDimensions: "29 to 20",
      name: "Голият космонавт",
      enName: "The Naked Cosmonaut",
      technique: "акрил, смесена техника",
      enTechnique: "acrylic, mixed media",
      продадена: false,
      sold: false,
    }, 
    {
      key: "8",
      height: 35,
      width: 25,
      dimensions: "35 на 25",
      enDimensions: "35 to 25",
      name: "Мрачен бъбрек-ембрион",
      enName: "Dark Kidney Embryo",
      technique: "акрил, смесена техника",
      enTechnique: "acrylic, mixed media",
      продадена: false,
      sold: false,
    },
    {
      key: "9",
      height: 35,
      width: 25,
      dimensions: "35 на 25",
      enDimensions: "35 to 25",
      name: "Пиле на сивия пазар",
      enName: "Chicken On The Gray Market",
      technique: "акрил, смесена техника",
      enTechnique: "acrylic, mixed media",
      продадена: false,
      sold: false,
    },
    {
      key: "10",
      height: 30,
      width: 25,
      dimensions: "30 на 25",
      enDimensions: "30 to 25",
      name: "Шеф",
      enName: "Boss",
      technique: "акрил, смесена техника",
      enTechnique: "acrylic, mixed media",
      продадена: false,
      sold: false,
    },
    {
      key: "11",
      height: 33,
      width: 25,
      dimensions: "33 на 25",
      enDimensions: "33 to 25",
      name: "Мементо мори",
      enName: "Memento Mori",
      technique: "акрил, смесена техника",
      enTechnique: "acrylic, mixed media",
      продадена: false,
      sold: false,
    }, 
    {
      key: "12",
      height: 30,
      width: 20,
      dimensions: "30 на 20",
      enDimensions: "30 to 20",
      name: "Степната вълчица",
      enName: "The Steppen Wolf",
      technique: "акрил, смесена техника",
      enTechnique: "acrylic, mixed media",
      продадена: false,
      sold: false,
    }, 
    {
      key: "13",
      height: 20,
      width: 15,
      dimensions: "20 на 15",
      enDimensions: "20 to 15",
      name: "Алиса не е тук",
      enName: "Alice Is Not Here",
      technique: "акрил, смесена техника",
      enTechnique: "acrylic, mixed media",
      продадена: false,
      sold: false,
    },
    {
      key: "14",
      height: 20,
      width: 15,
      dimensions: "20 на 15",
      enDimensions: "20 to 15",
      name: "Котаракът анархист",
      enName: "Tomcat The Anarchist",
      technique: "акрил, смесена техника",
      enTechnique: "acrylic, mixed media",
      продадена: false,
      sold: false,
    },
    {
      key: "15",
      height: 21,
      width: 15,
      dimensions: "21 на 15",
      enDimensions: "21 to 15",
      name: "Летяща риба",
      enName: "Flying Fish",
      technique: "акрил, смесена техника",
      enTechnique: "acrylic, mixed media",
      продадена: false,
      sold: false,
    }, 
    {
      key: "16",
      height: 20,
      width: 15,
      dimensions: "20 на 15",
      enDimensions: "20 to 15",
      name: "Унищожение",
      enName: "Destruction",
      technique: "акрил, смесена техника",
      enTechnique: "acrylic, mixed media",
      продадена: false,
      sold: false,
    }, 
    {
      key: "17",
      height: 20,
      width: 16,
      dimensions: "20 на 16",
      enDimensions: "20 to 16",
      name: "Пиленца",
      enName: "Birds",
      technique: "акрил, смесена техника",
      enTechnique: "acrylic, mixed media",
      продадена: false,
      sold: false,
    },
    {
      key: "18",
      height: 20,
      width: 16,
      dimensions: "20 на 16",
      enDimensions: "20 to 16",
      name: "Зъбчо",
      enName: "Toothy",
      technique: "акрил, смесена техника",
      enTechnique: "acrylic, mixed media",
      продадена: false,
      sold: false,
    },
    {
      key: "19",
      height: 40,
      width: 30,
      dimensions: "40 на 30",
      enDimensions: "40 to 30",
      name: "Детстоукър",
      enName: "Deathstalker",
      technique: "акрил, смесена техника",
      enTechnique: "acrylic, mixed media",
      продадена: false,
      sold: false,
    },               
  ];

export default function Drawings() {

    return (
        <section className={classes.background}>
            <section className={classes.overlay}>
            <section className="container">
                {PAINTINGS.map(p => {
                    return (
                        <Painting
                            key={p.key}
                            src={`/drawings/${p.name}.jpg`}
                            alt={p.name}
                            technique={p.technique}
                            width={400 / (p.height / p.width)}
                            height={400}
                            dimensions={p.dimensions}
                            text={p.text}
                        />
                  );
                })}
            </section>
            </section> 
        </section>
    )
}